<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>updater.cfgver</RootNamespace>
    <AssemblyName>updater.cfgver</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="migration_rules.yaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="12.0.2" />
  </ItemGroup>
</Project>